title: Mark Gillespie # your name (or website title) here
logo: "/images/head shot.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/markjgillespie/">View My LinkedIn Profile</a> 
  
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

minima:
  skin: dark

